database:
  driver: sqlite
  dsn: "examples/example.db"

output:
  dir: "./generated"
  package: "model"

tables:
  include: ["users", "products", "orders", "order_items"]
  exclude: []
  prefix: ""

options:
  generate_dao: true
  generate_sql: true
  json_tag: true
  generate_example: true  # 启用 Example 功能，支持复杂查询
  namespace_format: "dao.{struct}DAO"  # XML namespace 格式：包名.DAO接口名