database:
  driver: sqlite
  dsn: "./example.db"

output:
  dir: "./generated"
  package: "model"

tables:
  include: ["users", "products", "orders", "order_items"]
  exclude: []
  prefix: ""

options:
  generate_dao: true
  generate_sql: true
  json_tag: true
  generate_example: true
  # XML namespace 自定义格式配置
  # 支持 {struct} 占位符，会被替换为结构体名称
  # 默认值: "{struct}DAO"
  # 示例配置:
  namespace_format: "{struct}DAO"        # 默认格式: UsersDAO, ProductsDAO
  # namespace_format: "{struct}Mapper"   # 自定义格式: UsersMapper, ProductsMapper  
  # namespace_format: "com.example.{struct}DAO"  # 带包名格式: com.example.UsersDAO
  # namespace_format: "{struct}"         # 仅结构体名: Users, Products